line-height = 1.1
theme = "transparency"

[cursor]
shape = "beam"

[editor]
program = "hx"

[fonts]
size = 18

[fonts.regular]
family = "Rec Mono Casual"
style = "Italic"

[navigation]
current-working-directory = true
mode = "BottomTab"

[renderer]
performance = "High"
backend = "Automatic"

[title]
content = " {{ PROGRAM }} "

[window]
decorations = "Disabled"
mode = "Maximized"

[window.background-image]
# opacity = 0.2 # broken for the last year or so
path = "fire2.jpg"

[bindings]
keys = [
  # Tabs
  { key = "n", with = "alt", action = "CreateTab" },
  { key = "x", with = "alt", action = "CloseSplitOrTab" },
  
  # Panes
  { key = "p", with = "alt", action = "SplitRight" },
  { key = "p", with = "alt | shift", action = "SplitDown" },
  
  # Navigation
  { key = "h", with = "alt", action = "SelectPrevSplitOrTab" },
  { key = "j", with = "alt", action = "SelectNextSplit" },
  { key = "k", with = "alt", action = "SelectPrevSplit" },
  { key = "l", with = "alt", action = "SelectNextSplitOrTab" },
  { key = "j", with = "control | alt", action = "Scroll(-3)" },
  { key = "k", with = "control | alt", action = "Scroll(3)" },
  { key = "home", with = "control | alt", action = "ScrollToTop" },
  { key = "end", with = "control | alt", action = "ScrollToBottom" },
  { key = "pageup", with = "control | alt", action = "ScrollPageUp" },
  { key = "pagedown", with = "control | alt", action = "ScrollPageDown" },
  { key = "/", with = "control | alt", action = "" },

  # VI Mode
  { key = "esc", mode = "vi", action = "ToggleVIMode" },
  { key = "esc", mode = "~vi", action = "ToggleVIMode" },
  
  # Copy/paste (common defaults)
  { key = "c", with = "super", action = "Copy" },
  { key = "v", with = "super", action = "Paste" },
  
  
  # Open config editor (Ctrl+Shift+, in wezterm)
  { key = "comma", with = "control | shift", action = "OpenConfigEditor" },
]
